version: '3.8'

services:
  # Backend - Java Spring Boot (porta 8080)
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  # Frontend - React + Nginx (porta 3000)
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
